// Report HTML generation.
//
// Scanned data (SSIDs especially) is attacker-controlled: a nearby AP can
// broadcast an ESSID containing markup. The on-screen Vue tables escape it, but
// this module builds a standalone HTML document by string concatenation, so every
// dynamic value must be escaped here or it becomes live markup in the exported
// file. A locked-down CSP in the generated document is the backstop.

export function escapeHtml(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

export function buildHtmlReport(data) {
  const { config = {}, generatedAt = '', networks = [], summary = {}, captureFiles = [], interfaces = [] } = data || {}
  const ts = escapeHtml(generatedAt)
  const aps = [...networks].sort((a, b) => b.dbm - a.dbm)

  const secBreakdown = (() => {
    if (!aps.length) return ''
    const g = {}
    for (const ap of aps) {
      const k = ap.privacy || 'OPN'
      g[k] = (g[k] || 0) + 1
    }
    return Object.entries(g)
      .sort((a, b) => b[1] - a[1])
      .map(
        ([p, c]) =>
          `<tr><td>${escapeHtml(p)}</td><td>${escapeHtml(c)}</td><td>${Math.round((c / aps.length) * 100)}%</td></tr>`,
      )
      .join('')
  })()

  const networksRows = aps
    .map(
      (ap) =>
        `<tr>
          <td style="font-family:monospace">${escapeHtml(ap.bssid)}</td>
          <td>${ap.essid ? escapeHtml(ap.essid) : '<i>hidden</i>'}</td>
          <td>${escapeHtml(ap.channel)}</td>
          <td>${escapeHtml(ap.dbm)} dBm</td>
          <td>${escapeHtml(ap.privacy)}</td>
          <td>${escapeHtml(ap.clientCount)}</td>
        </tr>`,
    )
    .join('')

  const captureRows = captureFiles
    .map(
      (f) =>
        `<tr><td style="font-family:monospace">${escapeHtml(f.filename)}</td><td>${escapeHtml(f.size_human)}</td></tr>`,
    )
    .join('')

  const ifaceRows = interfaces
    .map(
      (i) =>
        `<tr>
          <td style="font-family:monospace">${escapeHtml(i.interface)}</td>
          <td>${escapeHtml(i.driver || '')}</td>
          <td>${i.monitor_mode ? 'Monitor' : 'Managed'}</td>
        </tr>`,
    )
    .join('')

  const title = escapeHtml(config.title)
  const author = escapeHtml(config.author)
  const scope = escapeHtml(config.scope)
  const notes = escapeHtml(config.notes)

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:;">
<title>${title}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1e293b; line-height: 1.6; padding: 40px; }
  h1 { font-size: 2rem; color: #0f172a; margin-bottom: 4px; }
  h2 { font-size: 1.1rem; color: #334155; margin: 32px 0 12px; border-bottom: 2px solid #e2e8f0; padding-bottom: 6px; }
  .meta { color: #64748b; font-size: 0.85rem; margin-bottom: 32px; }
  .meta span { margin-right: 24px; }
  .tiles { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-bottom: 32px; }
  .tile { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 20px; text-align: center; }
  .tile .num { font-size: 2.5rem; font-weight: 700; color: #0f172a; }
  .tile .lbl { font-size: 0.75rem; color: #94a3b8; text-transform: uppercase; letter-spacing: .05em; margin-top: 4px; }
  table { width: 100%; border-collapse: collapse; font-size: 0.85rem; margin-bottom: 24px; }
  th { background: #f1f5f9; padding: 8px 12px; text-align: left; color: #475569; font-weight: 600; border-bottom: 1px solid #e2e8f0; }
  td { padding: 7px 12px; border-bottom: 1px solid #f1f5f9; vertical-align: middle; }
  tr:last-child td { border-bottom: none; }
  .notes { background: #f8fafc; border-left: 4px solid #3b82f6; padding: 16px 20px; border-radius: 0 8px 8px 0; white-space: pre-wrap; font-size: 0.9rem; color: #334155; margin-bottom: 16px; }
  .footer { margin-top: 48px; font-size: 0.75rem; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 16px; }
  @media print { body { padding: 20px; } .tiles { grid-template-columns: repeat(4, 1fr); } }
</style>
</head>
<body>
<h1>${title}</h1>
<div class="meta">
  ${author ? `<span>Author: <strong>${author}</strong></span>` : ''}
  ${scope ? `<span>Scope: <strong>${scope}</strong></span>` : ''}
  <span>Generated: <strong>${ts}</strong></span>
  <span>Generated by: <strong>AirmonGUI v0.2</strong></span>
</div>

${notes ? `<div class="notes">${notes}</div>` : ''}

<div class="tiles">
  <div class="tile"><div class="num">${escapeHtml(summary.interfaces)}</div><div class="lbl">Interfaces</div></div>
  <div class="tile"><div class="num">${escapeHtml(summary.networks)}</div><div class="lbl">Networks Found</div></div>
  <div class="tile"><div class="num">${escapeHtml(summary.clients)}</div><div class="lbl">Clients Found</div></div>
  <div class="tile"><div class="num">${escapeHtml(summary.captures)}</div><div class="lbl">Capture Files</div></div>
</div>

${
  ifaceRows
    ? `<h2>Wireless Interfaces</h2>
<table><thead><tr><th>Interface</th><th>Driver</th><th>Mode</th></tr></thead>
<tbody>${ifaceRows}</tbody></table>`
    : ''
}

${
  networksRows
    ? `<h2>Discovered Access Points (${aps.length})</h2>
<table><thead><tr><th>BSSID</th><th>ESSID</th><th>Channel</th><th>Signal</th><th>Security</th><th>Clients</th></tr></thead>
<tbody>${networksRows}</tbody></table>

<h2>Security Profile</h2>
<table><thead><tr><th>Protocol</th><th>Count</th><th>Share</th></tr></thead>
<tbody>${secBreakdown}</tbody></table>`
    : '<p style="color:#94a3b8;margin:16px 0">No scan data included in this report. Run a scan first.</p>'
}

${
  captureRows
    ? `<h2>Capture Files</h2>
<table><thead><tr><th>Filename</th><th>Size</th></tr></thead>
<tbody>${captureRows}</tbody></table>`
    : ''
}

<div class="footer">AirmonGUI &mdash; for authorised testing only &mdash; ${ts}</div>
</body>
</html>`
}
